### ISSUE TITLE
GET/ Summary 

### ISSUE THREAD

**Issue by Testingfor101** [MartinStoffel/tigo#4]
Great work, really nice that you contributed integration, I had been getting data as rest sensor in HA, but that was not very stable.
There is documented summary topic in Tigo API pdf [https://support.tigoenergy.com/hc/en-us/article_attachments/360041622173](url)
Would be really nice if you could add this to integration

**Comment by MartinStoffel** [comment]
Do you refer to page 26 and following?

**Comment by Testingfor101** [comment]
Yes, 26-27 pages.

Also, when it is night and no electricity is produced I am getting this error:
```typescript
Logger: custom_components.tigo.tigo
Source: helpers/update_coordinator.py:354
integration: Tigo cloud ([documentation](https://github.com/MartinStoffel/tigo))
First occurred: 9:00:53 AM (238 occurrences)
Last logged: 12:57:55 PM

Unexpected error fetching TigoCoordinator data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tigo/tigo.py", line 178, in _async_update_data
    return await self.tigo_data.fetch_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tigo/tigo.py", line 129, in fetch_data
    if self._lastTime != time:
                         ^^^^
UnboundLocalError: cannot access local variable 'time' where it is not associated with a value
```

**Comment by Testingfor101** [comment]
Have you tried maybe add this info to integration?

**Comment by MartinStoffel** [comment]
Hi @Testingfor101 

Took qute some time, but I just created a branch with the added sensors, you can try it out if you like.
Any feedback is welcome!

**Comment by Testingfor101** [comment]
I cannot select under download another branch than main

**Comment by MartinStoffel** [comment]
Thank you for testing. Just merged the changes to main.
