### ISSUE TITLE
Error when there is no production

### ISSUE THREAD

**Issue by MartinStoffel** [MartinStoffel/tigo#5]
Also, when it is night and no electricity is produced I am getting this error:
```typescript
Logger: custom_components.tigo.tigo
Source: helpers/update_coordinator.py:354
integration: Tigo cloud ([documentation](https://github.com/MartinStoffel/tigo))
First occurred: 9:00:53 AM (238 occurrences)
Last logged: 12:57:55 PM

Unexpected error fetching TigoCoordinator data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tigo/tigo.py", line 178, in _async_update_data
    return await self.tigo_data.fetch_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tigo/tigo.py", line 129, in fetch_data
    if self._lastTime != time:
                         ^^^^
UnboundLocalError: cannot access local variable 'time' where it is not associated with a value
``` 
All entities are blank and marked as unavailable.

_Originally posted by @Testingfor101 in https://github.com/MartinStoffel/tigo/issues/4#issuecomment-2408911357_

**Comment by MartinStoffel** [comment]
Just creatd a new Issue for this. 
What should we report if there is no data available - apart form the fact that the error should be resolved.

**Comment by Testingfor101** [comment]
At least put entities to zeros instead showing unavailable state. 
I think this has to do with API, as it sends no data when solar panels not producing electricity.
https://ei.tigoenergy.com/api-docs/index
For example, data aggregate:
```typescript
2024/10/12 18:26:00,0,0,0,0,0,0,0,2,2,0,2,0
2024/10/12 18:27:00,0,0,0,0,0,0,0,2,2,0,2,0
2024/10/12 18:28:00,0,0,0,0,0,,0,2,2,0,1,0
2024/10/12 18:29:00,0,0,0,0,0,,0,2,2,0,0,0
2024/10/12 18:30:00,1,0,0,0,0,,0,2,2,0,0,0
2024/10/12 18:31:00,0,0,0,0,0,,0,2,1,0,0,0
2024/10/12 18:32:00,0,0,0,0,0,,0,2,1,0,0,0
2024/10/12 18:33:00,0,0,0,0,0,,0,2,0,0,0,0
2024/10/12 18:34:00,1,0,0,0,0,,0,1,0,0,0,0
2024/10/12 18:35:00,0,0,0,0,0,,0,0,,,,
2024/10/12 18:36:00,1,0,0,0,0,,0,0,,,,
2024/10/12 18:37:00,1,0,0,0,0,,0,0,,,,
2024/10/12 18:38:00,1,0,0,0,0,,0,0,,,,
2024/10/12 18:39:00,1,0,0,0,0,,0,0,,,,
2024/10/12 18:40:00,1,0,0,0,,,0,0,,,,
2024/10/12 18:41:00,0,0,0,0,,,0,0,,,,
2024/10/12 18:42:00,0,0,,0,,,0,0,,,,
2024/10/12 18:43:00,0,0,,0,,,0,0,,,,
2024/10/12 18:44:00,0,0,,0,,,0,0,,,,
2024/10/12 18:45:00,0,0,,0,,,0,0,,,,
2024/10/12 18:46:00,0,0,,0,,,0,0,,,,
2024/10/12 18:47:00,0,0,,0,,,0,0,,,,
2024/10/12 18:48:00,0,0,,0,,,0,0,,,,
2024/10/12 18:49:00,0,0,,0,,,0,0,,,,
2024/10/12 18:50:00,0,0,,0,,,0,0,,,,
2024/10/12 18:51:00,0,0,,0,,,0,0,,,,
2024/10/12 18:52:00,0,0,,0,,,0,0,,,,
2024/10/12 18:53:00,0,0,,0,,,0,0,,,,
2024/10/12 18:54:00,0,0,,0,,,0,1,,,,
2024/10/12 18:55:00,0,0,,0,,,0,0,,,,
2024/10/12 18:56:00,0,0,,0,,,0,0,,,,
2024/10/12 18:57:00,0,0,,0,,,,,,,,
2024/10/12 18:58:00,0,0,,0,,,,,,,,
2024/10/12 18:59:00,0,0,,0,,,,,,,,
2024/10/12 19:00:00,0,,,0,,,,,,,,
2024/10/12 19:01:00,,,,,,,,,,,,
2024/10/12 19:02:00,,,,,,,,,,,,
2024/10/12 19:03:00,,,,,,,,,,,,
2024/10/12 19:04:00,,,,,,,,,,,,
2024/10/12 19:05:00,,,,,,,,,,,,
2024/10/12 19:06:00,,,,,,,,,,,,
2024/10/12 19:07:00,,,,,,,,,,,,
2024/10/12 19:08:00,,,,,,,,,,,,
2024/10/12 19:09:00,,,,,,,,,,,,
2024/10/12 19:10:00,,,,,,,,,,,,
2024/10/12 19:11:00,,,,,,,,,,,,
2024/10/12 19:12:00,,,,,,,,,,,,
2024/10/12 19:13:00,,,,,,,,,,,,
```

**Comment by Testingfor101** [comment]
Works well!

**Comment by Testingfor101** [comment]
Some of panels still at night shows _Unknown_ state. Is there reason for this?

![Screenshot_20241027_120227_Samsung Internet](https://github.com/user-attachments/assets/9a8ea9bb-4389-4fa4-9f49-7b4ad456b322)
![Screenshot_20241027_120221_Samsung Internet](https://github.com/user-attachments/assets/81cfa888-f557-4389-aa49-a69739da2806)
![Screenshot_20241027_120210_Samsung Internet](https://github.com/user-attachments/assets/496bfbea-5c1f-4af0-a0f9-d33cb2c45d69)
![Screenshot_20241027_120200_Samsung Internet](https://github.com/user-attachments/assets/3d7baf78-0668-4efc-ae3d-4d61afefce79)
